version: 2
updates:
  - package-ecosystem: docker
    commit-message:
      prefix: "chore"
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: pip
    commit-message:
      prefix: chore
    directory: /tests
    schedule:
      interval: monthly
      day: saturday
    groups:
      python-test-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gitsubmodule
    commit-message:
      prefix: chore
    directory: /
    schedule:
      interval: monthly
      day: saturday
